version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:            # Load the .env file
      - .env
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}   # Use .env variable for DB password
      MYSQL_DATABASE: ${DB_NAME}            # Use .env variable for DB name
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
